### ISSUE TITLE
Translucent bar appears above TestPress

### ISSUE THREAD

**Issue by noisysocks** [pento/testpress#120]
A very subtle translucent bar appears between the TestPress window and the menu bar. Looks odd.

<img width="360" alt="ready" src="https://user-images.githubusercontent.com/612155/55048921-12160a80-509e-11e9-9682-9e915a79ac3c.png">

**Comment by noisysocks** [comment]
I'm thinking this happens because of the border radius that Electron applies to the `BrowserWindow`. It doesn't look like this can be disabled (https://github.com/electron/electron/issues/414), so my inclination is to ditch the tray pointer in TestPress altogether.

**Comment by pento** [comment]
This is actually [a bug in MacOS](https://github.com/electron/electron/issues/13164#issuecomment-462099631).

**Comment by pento** [comment]
While there's no timeline for when this bug might be fixed in MacOS, I'm leaning towards just waiting it out. Putting the window right up against the tray is how tray menus looks, so it feels kind of weird for it to not be a menu in that case.

@karmatosed: Do you have thoughts on this?

**Comment by karmatosed** [comment]
It's hard to tell but I think Evernote also suffers from this?

![2019-04-01 at 09 17](https://user-images.githubusercontent.com/253067/55313178-0db36e00-545f-11e9-8227-d646ee59f823.jpg)

I would say stay with the issue if a bug that's not ours. As it's not a menu treating it how Evernote and other 'interaction apps' do is better.

**Comment by pento** [comment]
Cool, thanks for your feedback, @karmatosed!

**Comment by johnnybenson** [comment]
![image](https://user-images.githubusercontent.com/238022/84547527-bbf8ab80-acd1-11ea-98e0-aa71ef187314.png)

It's still a thing
