### ISSUE TITLE
Forked wordpress develop doesn't run in TestPress

### ISSUE THREAD

**Issue by draganescu** [pento/testpress#148]
**Describe the bug**
 I cloned a fork of [wordpress-develop](https://github.com/draganescu/wordpress-develop) and setup Testpress to use that as WP folder. I waited for everything to be OK and then visiting `http://localhost:9999` WP install starts and whatever I tried it says 
> Error establishing a database connection

**To Reproduce**
1. Make a fork of Wordpress/wordpress-develop
2. Clone that repo
3. Set test press to use it as `worpress folder`
4. Visit site
5. See problem

**Expected behavior**
To work just as the wordpress git repo does.

**Device:**
 - OS and Version: OSX
 - TestPress Version: latest

**Comment by draganescu** [comment]
@azaozz had a simiar problem on setting up the windows version and @pento suggested the fix would be:

> We need to create `wp-config.php` in `src`, not `build`.

**Comment by draganescu** [comment]
@pento is this a duplicate of #145 ?

**Comment by pento** [comment]
Yah, it sounds like it could be a duplicate. Easy way to check is to run `grunt build` in your WordPress folder, then try starting TestPress again.

**Comment by draganescu** [comment]
closing as a duplicate of #145
