### ISSUE TITLE
Add eslint

### ISSUE THREAD

**Issue by talldan** [pento/testpress#95]
Enable eslint for developers of testpress.

It'd be great to use `@wordpress/eslint-plugin`:
https://github.com/WordPress/gutenberg/tree/master/packages/eslint-plugin

**Comment by noisysocks** [comment]
Should be able to get this all from `@wordpress/scripts`.

https://github.com/WordPress/gutenberg/tree/master/packages/scripts

**Comment by noisysocks** [comment]
Fixed by https://github.com/pento/testpress/pull/97.
